#!/bin/bash

sudo wpa_cli -i wlan0 add_network
sudo wpa_cli -i wlan0 set_network 1  ssid '"CM5D91-8ECAF203C427-11CC85"'
sudo wpa_cli -i wlan0 set_network 1 key_mgmt NONE
sudo wpa_cli -i wlan0 enable_network 1
sudo wpa_cli -i wlan0 select_network 1

