#!/bin/bash

sudo wpa_cli -i wlan0 set_network 0  ssid '"UCInet Mobile Access"'
sudo wpa_cli -i wlan0 set_network 0 key_mgmt NONE
sudo wpa_cli -i wlan0 enable_network 0
sudo wpa_cli -i wlan0 select_network 0

